package com.ylab.repository.impl;

import com.ylab.exception.AuditReadException;
import com.ylab.exception.AuditWriteException;
import com.ylab.model.AuditModel;
import com.ylab.repository.AuditDao;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.util.List;
import java.util.Objects;

import static com.ylab.util.DataResultAuditQuery.getSelectAuditMessage;
import static com.ylab.util.DataResultAuditQuery.insertAuditMessage;

/**
 * AuditDaoImpl class represents an implementation of AuditDao interface for managing audit messages.
 * <p>
 * This class utilizes JdbcTemplate to send and retrieve audit messages from the database.
 *
 * @author razlivinsky
 * @since 14.05.2024
 */
@Repository
public class AuditDaoImpl implements AuditDao {
    private final JdbcTemplate jdbcTemplate;

    /**
     * Instantiates a new Audit dao.
     *
     * @param jdbcTemplate the jdbc template
     */
    public AuditDaoImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Sends an audit message to the database and sets the message ID generated by the database.
     *
     * @param audit the audit message to be sent
     * @throws AuditWriteException if the message sending fails
     */
    @Override
    public void sendMessage(AuditModel audit) {
        try {
            KeyHolder keyHolder = new GeneratedKeyHolder();
            jdbcTemplate.update(connection -> {
                PreparedStatement ps = connection.prepareStatement(insertAuditMessage(), new String[] {"id"});
                ps.setString(1, audit.getMessage());
                return ps;
            }, keyHolder);
            audit.setId(Objects.requireNonNull(keyHolder.getKey()).longValue());
        } catch (DataAccessException e) {
            throw new AuditWriteException("Failed to send message " + e.getMessage());
        }
    }

    /**
     * Retrieves all audit messages from the database.
     *
     * @return a list of all audit messages
     * @throws AuditReadException if the retrieval of audit messages fails
     */
    @Override
    public List<AuditModel> getMessage() {
        try {
            return jdbcTemplate.query(getSelectAuditMessage(), auditRowMapper);
        } catch (DataAccessException e) {
            throw new AuditReadException("Failed to retrieve all audit message " + e.getMessage());
        }
    }

    private final RowMapper<AuditModel> auditRowMapper = (rs, rowNum) -> {
        AuditModel audit = new AuditModel(rs.getString("message"));
        audit.setId(rs.getLong("id"));
        return audit;
    };
}