package com.ylab.app.dbService.dao.impl;

import com.ylab.app.dbService.dao.AuditDao;
import com.ylab.app.dbService.mappers.AuditRowMapper;
import com.ylab.app.exception.dbException.DatabaseReadException;
import com.ylab.app.exception.dbException.DatabaseWriteException;
import com.ylab.app.model.audit.AuditModel;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.*;
import java.util.List;
import java.util.Objects;

import static com.ylab.app.util.DataResultAuditQuery.getSelectAuditMessage;
import static com.ylab.app.util.DataResultAuditQuery.insertAuditMessage;

/**
 * AuditDaoImpl class represents an implementation of AuditDao interface for managing audit messages.
 * <p>
 * This class utilizes JdbcTemplate to send and retrieve audit messages from the database.
 *
 * @author razlivinsky
 * @since 02.05.2024
 */
@Repository
@RequiredArgsConstructor
public class AuditDaoImpl implements AuditDao {
    private final JdbcTemplate jdbcTemplate;
    private final AuditRowMapper auditRowMapper;

    /**
     * Sends an audit message to the database and sets the message ID generated by the database.
     *
     * @param audit the audit message to be sent
     * @throws DatabaseWriteException if the message sending fails
     */
    @Override
    public void sendMessage(AuditModel audit) {
        try {
            KeyHolder keyHolder = new GeneratedKeyHolder();
            jdbcTemplate.update(connection -> {
                PreparedStatement ps = connection.prepareStatement(insertAuditMessage(), new String[] {"id"});
                ps.setString(1, audit.getMessage());
                return ps;
            }, keyHolder);
            audit.setId(Objects.requireNonNull(keyHolder.getKey()).longValue());
        } catch (DataAccessException e) {
            throw new DatabaseWriteException("Failed to send message " + e.getMessage());
        }
    }

    /**
     * Retrieves all audit messages from the database.
     *
     * @return a list of all audit messages
     * @throws DatabaseReadException if the retrieval of audit messages fails
     */
    @Override
    public List<AuditModel> getMessage() {
        try {
            return jdbcTemplate.query(getSelectAuditMessage(), auditRowMapper);
        } catch (DataAccessException e) {
            throw new DatabaseReadException("Failed to retrieve all audit message " + e.getMessage());
        }
    }
}